export const data = [
  {
    insel: "Zypern",
    land: "Zypern",
    googleSuchanfragen: 4760,
    tikTokHashtags: 1800000,
    strandeBlaueFlagge: 77,
    wasserTemperatur: 19.8,
    sicherheit: 80.2,
    visum: "Nein",
    outdoorAktivitaten: 653,
    regentage: 4.6,
    sonnenstunden: 9,
    bierpreis: 5,
    direktflugverbindungen: "Ja",
    score: 79,
  },
  {
    insel: "Teneriffa",
    land: "Spanien",
    googleSuchanfragen: 4880,
    tikTokHashtags: 787100,
    strandeBlaueFlagge: 16,
    wasserTemperatur: 20.6,
    sicherheit: 82.2,
    visum: "Nein",
    outdoorAktivitaten: 662,
    regentage: 4.9,
    sonnenstunden: 7.4,
    bierpreis: 2,
    direktflugverbindungen: "Ja",
    score: 76,
  },
  {
    insel: "Malta",
    land: "Malta",
    googleSuchanfragen: 3350,
    tikTokHashtags: 785300,
    strandeBlaueFlagge: 10,
    wasserTemperatur: 18.1,
    sicherheit: 85.6,
    visum: "Nein",
    outdoorAktivitaten: 629,
    regentage: 5.6,
    sonnenstunden: 8.9,
    bierpreis: 4,
    direktflugverbindungen: "Ja",
    score: 75,
  },
  {
    insel: "Mallorca",
    land: "Spanien",
    googleSuchanfragen: 8110,
    tikTokHashtags: 758600,
    strandeBlaueFlagge: 20,
    wasserTemperatur: 17,
    sicherheit: 82.2,
    visum: "Nein",
    outdoorAktivitaten: 652,
    regentage: 4.9,
    sonnenstunden: 8.3,
    bierpreis: 3,
    direktflugverbindungen: "Ja",
    score: 75,
  },
  {
    insel: "Kreta",
    land: "Griechenland",
    googleSuchanfragen: 4460,
    tikTokHashtags: 274500,
    strandeBlaueFlagge: 146,
    wasserTemperatur: 18.3,
    sicherheit: 74.2,
    visum: "Nein",
    outdoorAktivitaten: 1000,
    regentage: 6,
    sonnenstunden: 7.5,
    bierpreis: 3.3,
    direktflugverbindungen: "Ja",
    score: 74,
  },
  {
    insel: "Gran Canaria",
    land: "Spanien",
    googleSuchanfragen: 2610,
    tikTokHashtags: 310400,
    strandeBlaueFlagge: 14,
    wasserTemperatur: 19.2,
    sicherheit: 82.2,
    visum: "Nein",
    outdoorAktivitaten: 384,
    regentage: 5,
    sonnenstunden: 7.5,
    bierpreis: 2,
    direktflugverbindungen: "Ja",
    score: 72,
  },
  {
    insel: "Fuerteventura",
    land: "Spanien",
    googleSuchanfragen: 3700,
    tikTokHashtags: 142100,
    strandeBlaueFlagge: 10,
    wasserTemperatur: 19.8,
    sicherheit: 82.2,
    visum: "Nein",
    outdoorAktivitaten: 170,
    regentage: 1.5,
    sonnenstunden: 7.5,
    bierpreis: 2.5,
    direktflugverbindungen: "Ja",
    score: 71,
  },
  {
    insel: "Ibiza",
    land: "Spanien",
    googleSuchanfragen: 1710,
    tikTokHashtags: 937600,
    strandeBlaueFlagge: 6,
    wasserTemperatur: 17.3,
    sicherheit: 82.2,
    visum: "Nein",
    outdoorAktivitaten: 323,
    regentage: 4.1,
    sonnenstunden: 8.8,
    bierpreis: 4,
    direktflugverbindungen: "Ja",
    score: 70,
  },
  {
    insel: "Sizilien",
    land: "Italien",
    googleSuchanfragen: 3590,
    tikTokHashtags: 565200,
    strandeBlaueFlagge: 16,
    wasserTemperatur: 17.3,
    sicherheit: 79,
    visum: "Nein",
    outdoorAktivitaten: 2000,
    regentage: 7.8,
    sonnenstunden: 7.3,
    bierpreis: 5,
    direktflugverbindungen: "Ja",
    score: 69,
  },
  {
    insel: "Dominikanische Republik",
    land: "Dominikanische Republik",
    googleSuchanfragen: 1060,
    tikTokHashtags: 535300,
    strandeBlaueFlagge: 22,
    wasserTemperatur: 27.4,
    sicherheit: 49.9,
    visum: "Ja",
    outdoorAktivitaten: 3000,
    regentage: 9.1,
    sonnenstunden: 7.9,
    bierpreis: 2.34,
    direktflugverbindungen: "Nein",
    score: 68,
  },
  {
    insel: "Hawaii",
    land: "USA",
    googleSuchanfragen: 800,
    tikTokHashtags: 2900000,
    strandeBlaueFlagge: 0,
    wasserTemperatur: 24.9,
    sicherheit: 66.2,
    visum: "Nein",
    outdoorAktivitaten: 2000,
    regentage: 4.1,
    sonnenstunden: 8.6,
    bierpreis: 1.81,
    direktflugverbindungen: "Nein",
    score: 68,
  },
  {
    insel: "Azoren",
    land: "Portugal",
    googleSuchanfragen: 3100,
    tikTokHashtags: 66800,
    strandeBlaueFlagge: 44,
    wasserTemperatur: 17.2,
    sicherheit: 83.1,
    visum: "Nein",
    outdoorAktivitaten: 644,
    regentage: 9.6,
    sonnenstunden: 6.2,
    bierpreis: 1.2,
    direktflugverbindungen: "Nein",
    score: 66,
  },
  {
    insel: "Rhodos",
    land: "Griechenland",
    googleSuchanfragen: 1400,
    tikTokHashtags: 31700,
    strandeBlaueFlagge: 54,
    wasserTemperatur: 19,
    sicherheit: 74.2,
    visum: "Nein",
    outdoorAktivitaten: 458,
    regentage: 6.8,
    sonnenstunden: 9.1,
    bierpreis: 5,
    direktflugverbindungen: "Ja",
    score: 66,
  },
  {
    insel: "Sardinien",
    land: "Italien",
    googleSuchanfragen: 3360,
    tikTokHashtags: 154200,
    strandeBlaueFlagge: 41,
    wasserTemperatur: 16.6,
    sicherheit: 79,
    visum: "Nein",
    outdoorAktivitaten: 681,
    regentage: 5.6,
    sonnenstunden: 7.6,
    bierpreis: 4,
    direktflugverbindungen: "Ja",
    score: 65,
  },
  {
    insel: "Mauritius",
    land: "Mauritius",
    googleSuchanfragen: 3210,
    tikTokHashtags: 1300000,
    strandeBlaueFlagge: 0,
    wasserTemperatur: 26.6,
    sicherheit: 73.5,
    visum: "Nein",
    outdoorAktivitaten: 561,
    regentage: 13.1,
    sonnenstunden: 7.5,
    bierpreis: 1.97,
    direktflugverbindungen: "Nein",
    score: 65,
  },
  {
    insel: "Korfu",
    land: "Griechenland",
    googleSuchanfragen: 1290,
    tikTokHashtags: 114400,
    strandeBlaueFlagge: 22,
    wasserTemperatur: 17.4,
    sicherheit: 74.2,
    visum: "Nein",
    outdoorAktivitaten: 447,
    regentage: 7.9,
    sonnenstunden: 8.1,
    bierpreis: 3,
    direktflugverbindungen: "Ja",
    score: 65,
  },
  {
    insel: "Madeira",
    land: "Portugal",
    googleSuchanfragen: 5190,
    tikTokHashtags: 269900,
    strandeBlaueFlagge: 12,
    wasserTemperatur: 19.6,
    sicherheit: 83.1,
    visum: "Nein",
    outdoorAktivitaten: 810,
    regentage: 8.4,
    sonnenstunden: 5.1,
    bierpreis: 2,
    direktflugverbindungen: "Ja",
    score: 64,
  },
  {
    insel: "Lanzarote",
    land: "Spanien",
    googleSuchanfragen: 1730,
    tikTokHashtags: 170700,
    strandeBlaueFlagge: 6,
    wasserTemperatur: 19.8,
    sicherheit: 82.2,
    visum: "Nein",
    outdoorAktivitaten: 231,
    regentage: 1.8,
    sonnenstunden: 7.5,
    bierpreis: 2.5,
    direktflugverbindungen: "Ja",
    score: 64,
  },
  {
    insel: "Kos",
    land: "Griechenland",
    googleSuchanfragen: 380,
    tikTokHashtags: 380600,
    strandeBlaueFlagge: 12,
    wasserTemperatur: 18.8,
    sicherheit: 74.2,
    visum: "Nein",
    outdoorAktivitaten: 80,
    regentage: 6,
    sonnenstunden: 9.1,
    bierpreis: 4.5,
    direktflugverbindungen: "Ja",
    score: 63,
  },
  {
    insel: "Bali",
    land: "Indonesien",
    googleSuchanfragen: 4170,
    tikTokHashtags: 5700000,
    strandeBlaueFlagge: 0,
    wasserTemperatur: 28.8,
    sicherheit: 51.6,
    visum: "Ja",
    outdoorAktivitaten: 5000,
    regentage: 17,
    sonnenstunden: 8.9,
    bierpreis: 2.83,
    direktflugverbindungen: "Nein",
    score: 61,
  },
  {
    insel: "Jamaika",
    land: "Jamaika",
    googleSuchanfragen: 390,
    tikTokHashtags: 2200000,
    strandeBlaueFlagge: 0,
    wasserTemperatur: 27.9,
    sicherheit: 65.6,
    visum: "Ja",
    outdoorAktivitaten: 4000,
    regentage: 11.3,
    sonnenstunden: 7.9,
    bierpreis: 2.19,
    direktflugverbindungen: "Nein",
    score: 61,
  },
  {
    insel: "Menorca",
    land: "Spanien",
    googleSuchanfragen: 390,
    tikTokHashtags: 88100,
    strandeBlaueFlagge: 5,
    wasserTemperatur: 16.9,
    sicherheit: 82.2,
    visum: "Nein",
    outdoorAktivitaten: 88,
    regentage: 5.8,
    sonnenstunden: 8.4,
    bierpreis: 2.5,
    direktflugverbindungen: "Ja",
    score: 61,
  },
  {
    insel: "Philippinen",
    land: "Philippinen",
    googleSuchanfragen: 980,
    tikTokHashtags: 10800000,
    strandeBlaueFlagge: 0,
    wasserTemperatur: 28.2,
    sicherheit: 45.1,
    visum: "Ja",
    outdoorAktivitaten: 1000,
    regentage: 6.1,
    sonnenstunden: 8.5,
    bierpreis: 1.3,
    direktflugverbindungen: "Nein",
    score: 60,
  },
  {
    insel: "Puerto Rico",
    land: "USA",
    googleSuchanfragen: 120,
    tikTokHashtags: 3500000,
    strandeBlaueFlagge: 1,
    wasserTemperatur: 27.1,
    sicherheit: 66.2,
    visum: "Nein",
    outdoorAktivitaten: 820,
    regentage: 11,
    sonnenstunden: 7.6,
    bierpreis: 2.77,
    direktflugverbindungen: "Nein",
    score: 59,
  },
  {
    insel: "Capri",
    land: "Italien",
    googleSuchanfragen: 140,
    tikTokHashtags: 204900,
    strandeBlaueFlagge: 2,
    wasserTemperatur: 16.8,
    sicherheit: 79,
    visum: "Nein",
    outdoorAktivitaten: 691,
    regentage: 7.9,
    sonnenstunden: 8.8,
    bierpreis: 4,
    direktflugverbindungen: "Ja",
    score: 59,
  },
  {
    insel: "Santorini",
    land: "Griechenland",
    googleSuchanfragen: 560,
    tikTokHashtags: 351000,
    strandeBlaueFlagge: 6,
    wasserTemperatur: 18,
    sicherheit: 74.2,
    visum: "Nein",
    outdoorAktivitaten: 1000,
    regentage: 5.3,
    sonnenstunden: 8.8,
    bierpreis: 5,
    direktflugverbindungen: "Ja",
    score: 58,
  },
  {
    insel: "Mykonos",
    land: "Griechenland",
    googleSuchanfragen: 420,
    tikTokHashtags: 264200,
    strandeBlaueFlagge: 1,
    wasserTemperatur: 17.5,
    sicherheit: 74.2,
    visum: "Nein",
    outdoorAktivitaten: 570,
    regentage: 5,
    sonnenstunden: 8.8,
    bierpreis: 4.75,
    direktflugverbindungen: "Ja",
    score: 58,
  },
  {
    insel: "Kap Verde",
    land: "Kap Verde",
    googleSuchanfragen: 1510,
    tikTokHashtags: 36400,
    strandeBlaueFlagge: 0,
    wasserTemperatur: 24.5,
    sicherheit: 70.8,
    visum: "Ja",
    outdoorAktivitaten: 328,
    regentage: 0.8,
    sonnenstunden: 9.4,
    bierpreis: 2.18,
    direktflugverbindungen: "Nein",
    score: 58,
  },
  {
    insel: "Formentera",
    land: "Spanien",
    googleSuchanfragen: 340,
    tikTokHashtags: 54200,
    strandeBlaueFlagge: 0,
    wasserTemperatur: 17,
    sicherheit: 82.2,
    visum: "Nein",
    outdoorAktivitaten: 67,
    regentage: 4.3,
    sonnenstunden: 8.9,
    bierpreis: 4,
    direktflugverbindungen: "Ja",
    score: 57,
  },
  {
    insel: "La Palma",
    land: "Spanien",
    googleSuchanfragen: 240,
    tikTokHashtags: 50000,
    strandeBlaueFlagge: 6,
    wasserTemperatur: 20.8,
    sicherheit: 82.2,
    visum: "Nein",
    outdoorAktivitaten: 34,
    regentage: 6.1,
    sonnenstunden: 7.6,
    bierpreis: 1.8,
    direktflugverbindungen: "Ja",
    score: 57,
  },
  {
    insel: "Bahamas",
    land: "Bahamas",
    googleSuchanfragen: 480,
    tikTokHashtags: 600600,
    strandeBlaueFlagge: 0,
    wasserTemperatur: 25.3,
    sicherheit: 67.8,
    visum: "Nein",
    outdoorAktivitaten: 590,
    regentage: 7.3,
    sonnenstunden: 8,
    bierpreis: 3.69,
    direktflugverbindungen: "Nein",
    score: 56,
  },
  {
    insel: "Phuket",
    land: "Thailand",
    googleSuchanfragen: 670,
    tikTokHashtags: 952300,
    strandeBlaueFlagge: 0,
    wasserTemperatur: 29.3,
    sicherheit: 53.7,
    visum: "Ja",
    outdoorAktivitaten: 1000,
    regentage: 11.8,
    sonnenstunden: 9.5,
    bierpreis: 2.42,
    direktflugverbindungen: "Nein",
    score: 55,
  },
  {
    insel: "Barbados",
    land: "Barbados",
    googleSuchanfragen: 160,
    tikTokHashtags: 240300,
    strandeBlaueFlagge: 0,
    wasserTemperatur: 27.8,
    sicherheit: 66.7,
    visum: "Nein",
    outdoorAktivitaten: 263,
    regentage: 11.8,
    sonnenstunden: 8.7,
    bierpreis: 2.21,
    direktflugverbindungen: "Nein",
    score: 55,
  },
  {
    insel: "Zakynthos",
    land: "Griechenland",
    googleSuchanfragen: 270,
    tikTokHashtags: 78700,
    strandeBlaueFlagge: 7,
    wasserTemperatur: 18,
    sicherheit: 74.2,
    visum: "Nein",
    outdoorAktivitaten: 176,
    regentage: 4.4,
    sonnenstunden: 8.4,
    bierpreis: 3.5,
    direktflugverbindungen: "Ja",
    score: 55,
  },
  {
    insel: "Taiwan",
    land: "Taiwan",
    googleSuchanfragen: 200,
    tikTokHashtags: 3000000,
    strandeBlaueFlagge: 0,
    wasserTemperatur: 23.1,
    sicherheit: 60.1,
    visum: "Nein",
    outdoorAktivitaten: 472,
    regentage: 12.1,
    sonnenstunden: 4.4,
    bierpreis: 2.81,
    direktflugverbindungen: "Ja",
    score: 55,
  },
  {
    insel: "Langkawi",
    land: "Malaysia",
    googleSuchanfragen: 0,
    tikTokHashtags: 430100,
    strandeBlaueFlagge: 0,
    wasserTemperatur: 29.3,
    sicherheit: 65.4,
    visum: "Nein",
    outdoorAktivitaten: 220,
    regentage: 14,
    sonnenstunden: 9.1,
    bierpreis: 1.37,
    direktflugverbindungen: "Nein",
    score: 55,
  },
  {
    insel: "Sansibar",
    land: "Tansania",
    googleSuchanfragen: 2110,
    tikTokHashtags: 485000,
    strandeBlaueFlagge: 0,
    wasserTemperatur: 28.4,
    sicherheit: 47.7,
    visum: "Ja",
    outdoorAktivitaten: 1000,
    regentage: 14.3,
    sonnenstunden: 7.9,
    bierpreis: 1.9,
    direktflugverbindungen: "Nein",
    score: 54,
  },
  {
    insel: "Seychellen",
    land: "Seychellen",
    googleSuchanfragen: 2500,
    tikTokHashtags: 92200,
    strandeBlaueFlagge: 0,
    wasserTemperatur: 28.7,
    sicherheit: 72.3,
    visum: "Nein",
    outdoorAktivitaten: 135,
    regentage: 14.3,
    sonnenstunden: 8.4,
    bierpreis: 5.3,
    direktflugverbindungen: "Nein",
    score: 53,
  },
  {
    insel: "Ischia",
    land: "Italien",
    googleSuchanfragen: 150,
    tikTokHashtags: 68300,
    strandeBlaueFlagge: 0,
    wasserTemperatur: 16.8,
    sicherheit: 79,
    visum: "Nein",
    outdoorAktivitaten: 82,
    regentage: 7.9,
    sonnenstunden: 8.3,
    bierpreis: 4,
    direktflugverbindungen: "Ja",
    score: 53,
  },
  {
    insel: "Korsika",
    land: "Frankreich",
    googleSuchanfragen: 1550,
    tikTokHashtags: 117700,
    strandeBlaueFlagge: 4,
    wasserTemperatur: 16.1,
    sicherheit: 84.6,
    visum: "Nein",
    outdoorAktivitaten: 56,
    regentage: 8.4,
    sonnenstunden: 7.6,
    bierpreis: 7,
    direktflugverbindungen: "Ja",
    score: 53,
  },
  {
    insel: "Koh Samui",
    land: "Thailand",
    googleSuchanfragen: 1390,
    tikTokHashtags: 132700,
    strandeBlaueFlagge: 0,
    wasserTemperatur: 28.9,
    sicherheit: 53.7,
    visum: "Ja",
    outdoorAktivitaten: 425,
    regentage: 11.8,
    sonnenstunden: 9.2,
    bierpreis: "2,03",
    direktflugverbindungen: "Nein",
    score: 52,
  },
  {
    insel: "Hvar",
    land: "Kroatien",
    googleSuchanfragen: 40,
    tikTokHashtags: 23000,
    strandeBlaueFlagge: 0,
    wasserTemperatur: 15.9,
    sicherheit: 74.2,
    visum: "Nein",
    outdoorAktivitaten: 227,
    regentage: 7.5,
    sonnenstunden: 8.4,
    bierpreis: 3,
    direktflugverbindungen: "Ja",
    score: 51,
  },
  {
    insel: "Bora-Bora",
    land: "Franzosisch-Polynesien",
    googleSuchanfragen: 120,
    tikTokHashtags: 112600,
    strandeBlaueFlagge: 9,
    wasserTemperatur: 28.3,
    sicherheit: 84.6,
    visum: "Nein",
    outdoorAktivitaten: 166,
    regentage: 20.8,
    sonnenstunden: 5.7,
    bierpreis: 4.3,
    direktflugverbindungen: "Nein",
    score: 51,
  },
  {
    insel: "Réunion",
    land: "Frankreich",
    googleSuchanfragen: 0,
    tikTokHashtags: 228900,
    strandeBlaueFlagge: 4,
    wasserTemperatur: 26.9,
    sicherheit: 84.6,
    visum: "Nein",
    outdoorAktivitaten: 52,
    regentage: 14.6,
    sonnenstunden: 7,
    bierpreis: 4.25,
    direktflugverbindungen: "Nein",
    score: 51,
  },
  {
    insel: "Rügen",
    land: "Deutschland",
    googleSuchanfragen: 700,
    tikTokHashtags: 24500,
    strandeBlaueFlagge: 4,
    wasserTemperatur: 6.6,
    sicherheit: 87.5,
    visum: "Nein",
    outdoorAktivitaten: 31,
    regentage: 9.1,
    sonnenstunden: 5.5,
    bierpreis: 3.8,
    direktflugverbindungen: "Ja",
    score: 49,
  },
  {
    insel: "Lombok",
    land: "Indonesien",
    googleSuchanfragen: 110,
    tikTokHashtags: 943600,
    strandeBlaueFlagge: 0,
    wasserTemperatur: 28.9,
    sicherheit: 51.6,
    visum: "Ja",
    outdoorAktivitaten: 426,
    regentage: 14.6,
    sonnenstunden: 8.8,
    bierpreis: 2.26,
    direktflugverbindungen: "Nein",
    score: 48,
  },
  {
    insel: "Usedom",
    land: "Deutschland",
    googleSuchanfragen: 340,
    tikTokHashtags: 13800,
    strandeBlaueFlagge: 9,
    wasserTemperatur: 6.6,
    sicherheit: 87.5,
    visum: "Nein",
    outdoorAktivitaten: 17,
    regentage: 8.3,
    sonnenstunden: 5.3,
    bierpreis: 3.9,
    direktflugverbindungen: "Nein*",
    score: 47,
  },
  {
    insel: "Koh Phi Phi",
    land: "Thailand",
    googleSuchanfragen: 60,
    tikTokHashtags: 21300,
    strandeBlaueFlagge: 0,
    wasserTemperatur: 29.3,
    sicherheit: 53.7,
    visum: "Ja",
    outdoorAktivitaten: 303,
    regentage: 11.8,
    sonnenstunden: 9.5,
    bierpreis: 2.5,
    direktflugverbindungen: "Nein",
    score: 45,
  },
  {
    insel: "Sylt",
    land: "Deutschland",
    googleSuchanfragen: 1340,
    tikTokHashtags: 44900,
    strandeBlaueFlagge: 0,
    wasserTemperatur: 8.5,
    sicherheit: 87.5,
    visum: "Nein",
    outdoorAktivitaten: 18,
    regentage: 10.4,
    sonnenstunden: 5.3,
    bierpreis: 4.5,
    direktflugverbindungen: "Ja",
    score: 45,
  },
  {
    insel: "Neukaledonien",
    land: "Frankreich",
    googleSuchanfragen: 0,
    tikTokHashtags: 73400,
    strandeBlaueFlagge: 0,
    wasserTemperatur: 25.6,
    sicherheit: 84.6,
    visum: "Nein",
    outdoorAktivitaten: 65,
    regentage: 10.9,
    sonnenstunden: 7.1,
    bierpreis: 8.38,
    direktflugverbindungen: "Nein",
    score: 44,
  },
  {
    insel: "Norderney",
    land: "Deutschland",
    googleSuchanfragen: 480,
    tikTokHashtags: 8311,
    strandeBlaueFlagge: 0,
    wasserTemperatur: 8.5,
    sicherheit: 87.5,
    visum: "Nein",
    outdoorAktivitaten: 21,
    regentage: 10.4,
    sonnenstunden: 5.4,
    bierpreis: 4.4,
    direktflugverbindungen: "Nein*",
    score: 44,
  },
  {
    insel: "Fidschi",
    land: "Fidschi",
    googleSuchanfragen: 0,
    tikTokHashtags: 529700,
    strandeBlaueFlagge: 0,
    wasserTemperatur: 28.4,
    sicherheit: 67.3,
    visum: "Ja",
    outdoorAktivitaten: 462,
    regentage: 16.4,
    sonnenstunden: 7.6,
    bierpreis: 6.5,
    direktflugverbindungen: "Nein",
    score: 43,
  },
  {
    insel: "Amrum",
    land: "Deutschland",
    googleSuchanfragen: 200,
    tikTokHashtags: 2886,
    strandeBlaueFlagge: 0,
    wasserTemperatur: 8.5,
    sicherheit: 87.5,
    visum: "Nein",
    outdoorAktivitaten: 21,
    regentage: 10.1,
    sonnenstunden: 5.5,
    bierpreis: 4,
    direktflugverbindungen: "Nein*",
    score: 43,
  },
  {
    insel: "Borkum",
    land: "Deutschland",
    googleSuchanfragen: 430,
    tikTokHashtags: 3905,
    strandeBlaueFlagge: 0,
    wasserTemperatur: 8.6,
    sicherheit: 87.5,
    visum: "Nein",
    outdoorAktivitaten: 31,
    regentage: 10.6,
    sonnenstunden: 5.5,
    bierpreis: 4.1,
    direktflugverbindungen: "Nein*",
    score: 43,
  },
  {
    insel: "Java",
    land: "Indonesien",
    googleSuchanfragen: 30,
    tikTokHashtags: 1683,
    strandeBlaueFlagge: 0,
    wasserTemperatur: 29.2,
    sicherheit: 51.6,
    visum: "Ja",
    outdoorAktivitaten: 1000,
    regentage: 18,
    sonnenstunden: 8.5,
    bierpreis: 1.98,
    direktflugverbindungen: "Nein",
    score: 42,
  },
  {
    insel: "Cook Inseln",
    land: "UK",
    googleSuchanfragen: 0,
    tikTokHashtags: 31000,
    strandeBlaueFlagge: 0,
    wasserTemperatur: 26.6,
    sicherheit: 63.5,
    visum: "Nein",
    outdoorAktivitaten: 24,
    regentage: 12,
    sonnenstunden: 7.8,
    bierpreis: 4.24,
    direktflugverbindungen: "Nein",
    score: 42,
  },
  {
    insel: "Bornholm",
    land: "Dänemark",
    googleSuchanfragen: 90,
    tikTokHashtags: 11400,
    strandeBlaueFlagge: 1,
    wasserTemperatur: 6.2,
    sicherheit: 92.2,
    visum: "Nein",
    outdoorAktivitaten: 5,
    regentage: 8.9,
    sonnenstunden: 5.4,
    bierpreis: 1.7,
    direktflugverbindungen: "Nein",
    score: 41,
  },
  {
    insel: "Fehmarn",
    land: "Deutschland",
    googleSuchanfragen: 50,
    tikTokHashtags: 10800,
    strandeBlaueFlagge: 0,
    wasserTemperatur: 6.6,
    sicherheit: 87.5,
    visum: "Nein",
    outdoorAktivitaten: 43,
    regentage: 9.9,
    sonnenstunden: 5.3,
    bierpreis: 4.2,
    direktflugverbindungen: "Ja",
    score: 40,
  },
  {
    insel: "Langeoog",
    land: "Deutschland",
    googleSuchanfragen: 120,
    tikTokHashtags: 2375,
    strandeBlaueFlagge: 0,
    wasserTemperatur: 8.3,
    sicherheit: 87.5,
    visum: "Nein",
    outdoorAktivitaten: 12,
    regentage: 10.4,
    sonnenstunden: 5.4,
    bierpreis: 4.4,
    direktflugverbindungen: "Ja",
    score: 40,
  },
  {
    insel: "Gili Inseln",
    land: "Indonesien",
    googleSuchanfragen: 0,
    tikTokHashtags: 21100,
    strandeBlaueFlagge: 0,
    wasserTemperatur: 28.9,
    sicherheit: 51.6,
    visum: "Ja",
    outdoorAktivitaten: 75,
    regentage: 14.6,
    sonnenstunden: 8.8,
    bierpreis: 3,
    direktflugverbindungen: "Nein",
    score: 38,
  },
  {
    insel: "Föhr",
    land: "Deutschland",
    googleSuchanfragen: 20,
    tikTokHashtags: 3006,
    strandeBlaueFlagge: 0,
    wasserTemperatur: 8.5,
    sicherheit: 87.5,
    visum: "Nein",
    outdoorAktivitaten: 19,
    regentage: 10.3,
    sonnenstunden: 5.4,
    bierpreis: 4.3,
    direktflugverbindungen: "Nein*",
    score: 38,
  },
  {
    insel: "Juist",
    land: "Deutschland",
    googleSuchanfragen: 40,
    tikTokHashtags: 3248,
    strandeBlaueFlagge: 0,
    wasserTemperatur: 8.6,
    sicherheit: 87.5,
    visum: "Nein",
    outdoorAktivitaten: 14,
    regentage: 10.4,
    sonnenstunden: 5.5,
    bierpreis: 4.7,
    direktflugverbindungen: "Nein*",
    score: 38,
  },
  {
    insel: "Spiekeroog",
    land: "Deutschland",
    googleSuchanfragen: 20,
    tikTokHashtags: 1386,
    strandeBlaueFlagge: 0,
    wasserTemperatur: 8.3,
    sicherheit: 87.5,
    visum: "Nein",
    outdoorAktivitaten: 12,
    regentage: 10.5,
    sonnenstunden: 5.3,
    bierpreis: 4.6,
    direktflugverbindungen: "Nein*",
    score: 38,
  },
  {
    insel: "Wangerooge",
    land: "Deutschland",
    googleSuchanfragen: 20,
    tikTokHashtags: 1658,
    strandeBlaueFlagge: 0,
    wasserTemperatur: 8.3,
    sicherheit: 87.5,
    visum: "Nein",
    outdoorAktivitaten: 5,
    regentage: 10.5,
    sonnenstunden: 5.3,
    bierpreis: 4.2,
    direktflugverbindungen: "Ja",
    score: 37,
  },
  {
    insel: "Papua-Neuguinea",
    land: "Papua-Neuguinea",
    googleSuchanfragen: 0,
    tikTokHashtags: 32300,
    strandeBlaueFlagge: 0,
    wasserTemperatur: 28.5,
    sicherheit: 57.3,
    visum: "Ja",
    outdoorAktivitaten: 8,
    regentage: 16.1,
    sonnenstunden: 8.8,
    bierpreis: 2.8,
    direktflugverbindungen: "Nein",
    score: 36,
  },
  {
    insel: "São Tomé und Príncipe",
    land: "Sao Tome",
    googleSuchanfragen: 0,
    tikTokHashtags: 2827,
    strandeBlaueFlagge: 0,
    wasserTemperatur: 22,
    sicherheit: 57.3,
    visum: "Ja",
    outdoorAktivitaten: 16,
    regentage: 16.6,
    sonnenstunden: 7.2,
    bierpreis: 1.01,
    direktflugverbindungen: "Nein",
    score: 34,
  },
];
